import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import UserList from '@/components/UserList'



export default function Home() {
  return (
    <>
      <Head>
        <title>Prueba técnica 310823</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <UserList></UserList>
      </main>
    </>
  )
}
